# Your Solution

version: '3.8'

services:
  book_catalog:
    image: book_catalog:latest
    build: 
      context: ./book_catalog
      platforms:
      - "linux/amd64"
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://part04_user:xuxzkAQukYtrPGuuCRwOTjBnE07ZWSnE@dpg-crrmskt6l47c73clfl1g-a.oregon-postgres.render.com/part04
    restart: "no"
    

  inventory_management:
    image: inventory_management:latest
    build: 
      context: ./inventory_management
      platforms:
      - "linux/amd64"
      dockerfile: Dockerfile
    ports:
      - "4001:4001" 
    environment:
      - DATABASE_URL=postgresql://part04_user:xuxzkAQukYtrPGuuCRwOTjBnE07ZWSnE@dpg-crrmskt6l47c73clfl1g-a.oregon-postgres.render.com/part04
    restart: "no"